const listActivity = [
  {
    title: 'Purchase by James Price',
    icon: 'material-symbols:shopping-cart-outline-rounded',
    color_icon: '#0ab39c',
    bg_icon: 'rgba(10,179,156,.18)',
    decripstion: 'Product noise evolve smartwatch',
    date: '02:14 PM Today',
  },
  {
    title: 'Added new style collection',
    icon: 'ph:stack-fill',
    color_icon: '#f06548',
    bg_icon: 'rgba(240,101,72,.18)',
    decripstion: 'By Nesta Technologies',
    date: '9:47 PM Yesterday',
  },
  {
    title: 'Today offers by Digitech Galaxy',
    icon: 'mdi:sale-circle',
    color_icon: '#ffff',
    bg_icon: '#3577f1',
    decripstion: 'Offer is valid on orders of Rs.500 Or above for selected products only.',
    date: '12 Dec, 2021',
  },
  {
    title: 'Purchase by James Price',
    icon: 'material-symbols:shopping-cart-outline-rounded',
    color_icon: '#0ab39c',
    bg_icon: 'rgba(10,179,156,.18)',
    decripstion: 'Product noise evolve smartwatch',
    date: '02:14 PM Today',
  },
  {
    title: 'Added new style collection',
    icon: 'ph:stack-fill',
    color_icon: '#f06548',
    bg_icon: 'rgba(240,101,72,.18)',
    decripstion: 'By Nesta Technologies',
    date: '9:47 PM Yesterday',
  },
  {
    title: 'Today offers by Digitech Galaxy',
    icon: 'mdi:sale-circle',
    color_icon: '#ffff',
    bg_icon: '#3577f1',
    decripstion: 'Offer is valid on orders of Rs.500 Or above for selected products only.',
    date: '12 Dec, 2021',
  },
  {
    title: 'Purchase by James Price',
    icon: 'material-symbols:shopping-cart-outline-rounded',
    color_icon: '#0ab39c',
    bg_icon: 'rgba(10,179,156,.18)',
    decripstion: 'Product noise evolve smartwatch',
    date: '02:14 PM Today',
  },
  {
    title: 'Added new style collection',
    icon: 'ph:stack-fill',
    color_icon: '#f06548',
    bg_icon: 'rgba(240,101,72,.18)',
    decripstion: 'By Nesta Technologies',
    date: '9:47 PM Yesterday',
  },
  {
    title: 'Today offers by Digitech Galaxy',
    icon: 'mdi:sale-circle',
    color_icon: '#ffff',
    bg_icon: '#3577f1',
    decripstion: 'Offer is valid on orders of Rs.500 Or above for selected products only.',
    date: '12 Dec, 2021',
  },
];
export default listActivity;
