export const Orders = [
  {
    id: 1,
    code: 'Order 1',
    name: 'Joseph Parker',
    address: '2186 Joyce Street Rocky Mount',
    phone: '+(256) 245451 451',
    email: 'josephparker@gmail.com',
    dateCreated: 'Wed, 15 Dec 2021',
    products: 5,
    total: 100000,
  },
  {
    id: 2,
    code: 'Order 1',
    name: 'Joseph Parker',
    address: '2186 Joyce Street Rocky Mount',
    phone: '+(256) 245451 451',
    email: 'josephparker@gmail.com',
    dateCreated: 'Wed, 15 Dec 2021',
    products: 5,
    total: 100000,
  },
  {
    id: 3,
    code: 'Order 1',
    name: 'Joseph Parker',
    address: '2186 Joyce Street Rocky Mount',
    phone: '+(256) 245451 451',
    email: 'josephparker@gmail.com',
    dateCreated: 'Wed, 15 Dec 2021',
    products: 5,
    total: 100000,
  },
  {
    id: 4,
    code: 'Order 1',
    name: 'Joseph Parker',
    address: '2186 Joyce Street Rocky Mount',
    phone: '+(256) 245451 451',
    email: 'josephparker@gmail.com',
    dateCreated: 'Wed, 15 Dec 2021',
    products: 5,
    total: 100000,
  },
  {
    id: 5,
    code: 'Order 1',
    name: 'Joseph Parker',
    address: '2186 Joyce Street Rocky Mount',
    phone: '+(256) 245451 451',
    email: 'josephparker@gmail.com',
    dateCreated: 'Wed, 15 Dec 2021',
    products: 5,
    total: 100000,
  },
];

export const deliveryOptions = [
  {
    name: 'All',
    _id: 'all',
  },
  {
    name: 'Pending',
    _id: 'pending',
  },
  {
    name: 'Delivered',
    _id: 'delivered',
  },
  {
    name: 'Inprogress',
    _id: 'inprogress',
  },
  {
    name: 'Returns',
    _id: 'returns',
  },
];
